sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
sudo ln -s /etc/sv/acpid /var/service/
