sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
sudo ln -s /etc/sv/acpid /var/service/acpid
