#sudo xbps-install -Syu dnsmasq openresolv
#sudo vim /etc/dnsmasq.conf
#sudo vim /etc/resolvdnsmasq.conf # nameserver 1.1.1.1 nameserver 1.0.0.1
#sudo xbps-install -Syu openresolv
#sudo vim /etc/resolvconf.conf # name_servers=127.0.0.1
#sudo vim /etc/resolv.conf
## Generated by resolvconf
#domain fastwebnet.it
#nameserver 127.0.0.1
#sudo ln -s /etc/sv/dnsmasq /var/service/
#sudo sv restart /var/service/dnsmasq
#sudo reboot
sudo xbps-install -Syu NetworkManager inetutils-ifconfig firefox firefox-i18n-ar firefox-i18n-en-US firefox-i18n-fr speech-dispatcher obfs4proxy tor curl tor torsocks qbittorrent