#doas xbps-install -Syu dnsmasq openresolv
#doas vim /etc/dnsmasq.conf
#doas vim /etc/resolvdnsmasq.conf # nameserver 1.1.1.1 nameserver 1.0.0.1
#doas xbps-install -Syu openresolv
#doas vim /etc/resolvconf.conf # name_servers=127.0.0.1
#doas vim /etc/resolv.conf
## Generated by resolvconf
#domain fastwebnet.it
#nameserver 127.0.0.1
#doas ln -s /etc/sv/dnsmasq /var/service/
#doas sv restart /var/service/dnsmasq
#doas reboot
doas xbps-install -Syu NetworkManager
doas xbps-install -Syu inetutils-ifconfig
doas xbps-install -Syu wget aria2 tor torsocks arp-scan obfs4proxy tor curl tor torsocks qbittorrent git
