sudo xbps-install -Syu dnsmasq openresolv
#sudo vim /etc/dnsmasq.conf
#sudo vim /etc/resolvdnsmasq.conf # nameserver 1.1.1.1 nameserver 1.0.0.1
sudo xbps-install -Syu openresolv
#sudo vim /etc/resolvconf.conf # name_servers=127.0.0.1
#sudo vim /etc/resolv.conf
## Generated by resolvconf
#domain fastwebnet.it
#nameserver 127.0.0.1
sudo ln -s /etc/sv/dnsmasq /var/service/
sudo sv restart /var/service/dnsmasq
#sudo reboot