#===========================[colors]================================#
[colors]
draw_bold_text_with_bright_colors = true
[colors.primary] # color de klfya # 5varoable
foreground = "#f8f8f2"
#background = "#282a36"
#background = "#333333"
background = "#222222"
bright_foreground = "#ffffff"
[colors.cursor]
cursor = "#0dbc79"
text = "#282a36"
[colors.vi_mode_cursor]
cursor = "#ff49c6"
text = "#83a598"
[colors.selection]
background = "#45403d"
text = "#cccccc"
[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#d0d0d0"
yellow = "#feff00"
[colors.bright]
black = "#666666"
blue = "#3b8eea"
cyan = "#29b8db"
green = "#23d18b"
magenta = "#d670d6"
red = "#f14c4c"
white = "#FFFFFF"
yellow = "#feff00"
#black = "#6272a4"
#blue = "#d6acff"
#cyan = "#a4ffff"
#green = "#69ff94"
#magenta = "#ff92df"
#red = "#ff6e6e"
#white = "#ffffff"
#yellow = "#ffffa5"
[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"
[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"
[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"
[colors.hints.start] # pour hints
background = "#f1fa8c"
foreground = "#282a36"
[colors.hints.end]  # pour hints ?
background = "#282a36"
foreground = "#f1fa8c"
