[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground        =  "#f8f8f2"
#background       =  "#222222"
#background       =  "#45403D"
background        =  "#333333"
#background       =  "#300A24"
#background       =  "#272700"
dim_foreground    =  "#828482"
bright_foreground =  "None"

[colors.cursor] # cursor-colors
cursor            = "#0dbc79"
text              = "#282a36"

[colors.vi_mode_cursor] # vi-cursor
cursor            = "#ff49c6"
text              = "#83a598"

[colors.search.matches]
background = "#feff00"
foreground = "#44475a"

[colors.search.focused_match]
background = "#feff00"
foreground = "#44475a"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection] # selection
background = "#45403d"
text       = "#cccccc"

[colors.normal]
black         = "#000000"
blue          = "#2472c8"
cyan          = "#11a8cd"
green         = "#0dbc79"
magenta       = "#bc3fbc"
red           = "#cd3131"
white         = "#d0d0d0"
yellow        = "#feff00"

[colors.bright]
black         = "#666666"
blue          = "#3b8eea"
cyan          = "#29b8db"
green         = "#23d18b"
magenta       = "#d670d6"
red           = "#f14c4c"
white         = "#FFFFFF"
yellow        = "#feff00"

[colors.footer_bar]
background        = "#282a36"
foreground        = "#f8f8f2"
